<?php
/**
 * Tools → Wellspring SEO — preview and import the ported meta values.
 *
 * Reads seo-migration/seo_data.json (generated by build_seo_data.py, never hand
 * edited) and shows, per target, the current value against the incoming one
 * BEFORE writing anything.
 *
 * Three properties this screen has to have:
 *
 *   1. Idempotent. Re-running writes nothing where the value already matches.
 *   2. Never silently clobbers a hand edit. Every write records a hash of what
 *      it wrote. If the live value no longer matches that hash, someone edited
 *      it since, and the row becomes a CONFLICT that must be ticked explicitly.
 *   3. A missing target is reported, never skipped. A page that was not created
 *      has to be visible, not quietly absent from the results.
 *
 * @package Wellspring
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

const WELLSPRING_SEO_DATA_FILE  = '/seo-migration/seo_data.json';
const WELLSPRING_SEO_IMPORT_CAP = 'manage_options';

/* -------------------------------------------------------------------------
 * Data
 * ---------------------------------------------------------------------- */

/**
 * Load the generated data file.
 *
 * @return array{ok:bool,error?:string,meta?:array,entries?:array}
 */
function wellspring_seo_import_data() {
	$path = get_template_directory() . WELLSPRING_SEO_DATA_FILE;

	if ( ! file_exists( $path ) ) {
		return array(
			'ok'    => false,
			'error' => sprintf(
				/* translators: %s: file path */
				__( 'Data file not found at %s. It is generated by build_seo_data.py and must be deployed with the theme.', 'wellspring' ),
				esc_html( WELLSPRING_SEO_DATA_FILE )
			),
		);
	}

	$raw = file_get_contents( $path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- local theme file.
	if ( false === $raw ) {
		return array( 'ok' => false, 'error' => __( 'Data file could not be read.', 'wellspring' ) );
	}

	$parsed = json_decode( $raw, true );
	if ( ! is_array( $parsed ) || empty( $parsed['entries'] ) ) {
		return array( 'ok' => false, 'error' => __( 'Data file is not valid JSON, or contains no entries.', 'wellspring' ) );
	}

	return array(
		'ok'      => true,
		'meta'    => isset( $parsed['_meta'] ) ? $parsed['_meta'] : array(),
		'entries' => $parsed['entries'],
	);
}

/**
 * Resolve one entry to something writable.
 *
 * @param array $entry Data-file entry.
 * @return array{kind:string,label:string,post_id?:int,error?:string}
 */
function wellspring_seo_import_target( $entry ) {
	$type = isset( $entry['target_type'] ) ? $entry['target_type'] : '';
	$key  = isset( $entry['target_key'] ) ? $entry['target_key'] : '';

	if ( 'front_page' === $type ) {
		$id = (int) get_option( 'page_on_front' );
		if ( ! $id ) {
			return array( 'kind' => 'missing', 'label' => __( 'front page', 'wellspring' ),
				'error' => __( 'No static front page is set (Settings → Reading).', 'wellspring' ) );
		}
		return array( 'kind' => 'post', 'label' => __( 'front page', 'wellspring' ), 'post_id' => $id );
	}

	if ( 'page' === $type ) {
		$page = get_page_by_path( $key );
		if ( ! $page instanceof WP_Post ) {
			return array(
				'kind'  => 'missing',
				'label' => 'page: ' . $key,
				'error' => sprintf(
					/* translators: %s: page slug */
					__( 'No published page with the slug “%s”. Create it, then re-run — nothing was written for this row.', 'wellspring' ),
					$key
				),
			);
		}
		if ( 'publish' !== $page->post_status ) {
			return array(
				'kind'  => 'missing',
				'label' => 'page: ' . $key,
				'error' => sprintf(
					/* translators: 1: slug, 2: post status */
					__( 'Page “%1$s” exists but its status is “%2$s”, not published.', 'wellspring' ),
					$key,
					$page->post_status
				),
			);
		}
		return array( 'kind' => 'post', 'label' => 'page: ' . $key, 'post_id' => (int) $page->ID );
	}

	if ( 'cpt_archive' === $type ) {
		if ( 'clinic_case' !== $key ) {
			return array( 'kind' => 'missing', 'label' => 'archive: ' . $key,
				'error' => __( 'Only the clinic_case archive has settings to write to.', 'wellspring' ) );
		}
		return array( 'kind' => 'theme_mod', 'label' => 'archive: clinic_case' );
	}

	return array( 'kind' => 'missing', 'label' => $type . ':' . $key,
		'error' => __( 'Unrecognised target type in the data file.', 'wellspring' ) );
}

/* -------------------------------------------------------------------------
 * Read / write one field
 * ---------------------------------------------------------------------- */

/**
 * Current stored value for a field on a target.
 *
 * @param array  $target Resolved target.
 * @param string $field  'title' | 'description'.
 * @return string
 */
function wellspring_seo_import_current( $target, $field ) {
	if ( 'theme_mod' === $target['kind'] ) {
		return (string) get_theme_mod( 'clinic_cases_seo_' . $field, '' );
	}
	if ( 'post' === $target['kind'] && function_exists( 'get_field' ) ) {
		return (string) get_field( 'seo_' . $field, $target['post_id'] );
	}
	return '';
}

/**
 * Hash of whatever this importer last wrote, so a later hand edit is detectable.
 *
 * @param array  $target Resolved target.
 * @param string $field  'title' | 'description'.
 * @return string
 */
function wellspring_seo_import_stamp( $target, $field ) {
	if ( 'theme_mod' === $target['kind'] ) {
		return (string) get_theme_mod( 'clinic_cases_seo_' . $field . '_import_sha', '' );
	}
	if ( 'post' === $target['kind'] ) {
		return (string) get_post_meta( $target['post_id'], '_ws_seo_import_sha_' . $field, true );
	}
	return '';
}

/**
 * Write a value and stamp it.
 *
 * @param array  $target Resolved target.
 * @param string $field  'title' | 'description'.
 * @param string $value  Value to write.
 * @return bool
 */
function wellspring_seo_import_write( $target, $field, $value ) {
	$sha = hash( 'sha256', $value );

	if ( 'theme_mod' === $target['kind'] ) {
		set_theme_mod( 'clinic_cases_seo_' . $field, $value );
		set_theme_mod( 'clinic_cases_seo_' . $field . '_import_sha', $sha );
		return true;
	}

	if ( 'post' === $target['kind'] ) {
		if ( ! function_exists( 'update_field' ) ) {
			return false;
		}
		update_field( 'seo_' . $field, $value, $target['post_id'] );
		update_post_meta( $target['post_id'], '_ws_seo_import_sha_' . $field, $sha );
		return true;
	}

	return false;
}

/**
 * Classify one field: what would happen if we wrote it now.
 *
 * @param array  $target   Resolved target.
 * @param string $field    'title' | 'description'.
 * @param string $incoming Incoming value ('' when there is nothing to port).
 * @return array{status:string,current:string,incoming:string,note:string}
 */
function wellspring_seo_import_plan_field( $target, $field, $incoming ) {
	$out = array( 'status' => '', 'current' => '', 'incoming' => (string) $incoming, 'note' => '' );

	if ( 'missing' === $target['kind'] ) {
		$out['status'] = 'missing';
		$out['note']   = isset( $target['error'] ) ? $target['error'] : '';
		return $out;
	}

	if ( '' === trim( (string) $incoming ) ) {
		$out['status'] = 'nothing';
		$out['note']   = __( 'Old site had no value for this field.', 'wellspring' );
		return $out;
	}

	$current         = wellspring_seo_import_current( $target, $field );
	$out['current']  = $current;

	if ( $current === $incoming ) {
		$out['status'] = 'unchanged';
		return $out;
	}

	if ( '' === trim( $current ) ) {
		$out['status'] = 'write';
		return $out;
	}

	// Differs and is non-empty: did we write what's there, or did a human?
	$stamp = wellspring_seo_import_stamp( $target, $field );
	if ( $stamp && hash( 'sha256', $current ) === $stamp ) {
		$out['status'] = 'update';
		$out['note']   = __( 'Current value was written by a previous import — safe to replace.', 'wellspring' );
		return $out;
	}

	$out['status'] = 'conflict';
	$out['note']   = __( 'Current value was not written by this importer. Tick to overwrite.', 'wellspring' );
	return $out;
}

/**
 * Build the full plan for every entry.
 *
 * @param array $entries Data-file entries.
 * @return array
 */
function wellspring_seo_import_plan( $entries ) {
	$plan = array();

	foreach ( $entries as $i => $entry ) {
		$target = wellspring_seo_import_target( $entry );

		$plan[] = array(
			'index'       => $i,
			'source_path' => isset( $entry['source_path'] ) ? $entry['source_path'] : '',
			'target'      => $target,
			'deviation'   => isset( $entry['deviation'] ) ? $entry['deviation'] : '',
			'fields'      => array(
				'title'       => wellspring_seo_import_plan_field(
					$target,
					'title',
					isset( $entry['title'] ) ? (string) $entry['title'] : ''
				),
				'description' => wellspring_seo_import_plan_field(
					$target,
					'description',
					isset( $entry['description'] ) ? (string) $entry['description'] : ''
				),
			),
		);
	}

	return $plan;
}

/* -------------------------------------------------------------------------
 * Admin screen
 * ---------------------------------------------------------------------- */

add_action(
	'admin_menu',
	function () {
		add_management_page(
			__( 'Wellspring SEO import', 'wellspring' ),
			__( 'Wellspring SEO', 'wellspring' ),
			WELLSPRING_SEO_IMPORT_CAP,
			'wellspring-seo-import',
			'wellspring_seo_import_screen'
		);
	}
);

/**
 * Render (and handle) the import screen.
 */
function wellspring_seo_import_screen() {
	if ( ! current_user_can( WELLSPRING_SEO_IMPORT_CAP ) ) {
		wp_die( esc_html__( 'You do not have permission to run the SEO import.', 'wellspring' ) );
	}

	$data    = wellspring_seo_import_data();
	$results = array();

	if ( $data['ok'] && isset( $_POST['ws_seo_import'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Missing -- checked immediately below.
		check_admin_referer( 'ws_seo_import' );
		$overwrite = isset( $_POST['ws_overwrite'] ) && is_array( $_POST['ws_overwrite'] )
			? array_map( 'sanitize_text_field', wp_unslash( $_POST['ws_overwrite'] ) )
			: array();
		$results = wellspring_seo_import_run( $data['entries'], $overwrite );
	}

	$plan = $data['ok'] ? wellspring_seo_import_plan( $data['entries'] ) : array();

	$labels = array(
		'write'     => array( __( 'Will write', 'wellspring' ), '#0F4D33', '#E8F4EE' ),
		'update'    => array( __( 'Will update', 'wellspring' ), '#0F4D33', '#E8F4EE' ),
		'unchanged' => array( __( 'Unchanged', 'wellspring' ), '#4A524E', '#F0F0F0' ),
		'nothing'   => array( __( 'Nothing to port', 'wellspring' ), '#6B7873', '#F6F6F6' ),
		'conflict'  => array( __( 'Conflict', 'wellspring' ), '#8A2B1D', '#FBE9E5' ),
		'missing'   => array( __( 'No target', 'wellspring' ), '#8A2B1D', '#FBE9E5' ),
	);
	?>
	<div class="wrap">
		<h1><?php esc_html_e( 'Wellspring SEO import', 'wellspring' ); ?></h1>

		<?php if ( ! $data['ok'] ) : ?>
			<div class="notice notice-error"><p><?php echo esc_html( $data['error'] ); ?></p></div>
			</div>
			<?php
			return;
		endif;
		?>

		<?php if ( wellspring_seo_plugin_active() ) : ?>
			<div class="notice notice-warning"><p>
				<?php esc_html_e( 'An SEO plugin is active, so the theme is not emitting meta. Values written here are stored but will not appear on the site until the plugin is deactivated.', 'wellspring' ); ?>
			</p></div>
		<?php endif; ?>

		<?php if ( ! function_exists( 'update_field' ) ) : ?>
			<div class="notice notice-error"><p>
				<?php esc_html_e( 'ACF is not active. Page and clinic-case values cannot be written.', 'wellspring' ); ?>
			</p></div>
		<?php endif; ?>

		<p class="description" style="max-width:none">
			<?php
			printf(
				/* translators: 1: capture timestamp, 2: number of deviations */
				esc_html__( 'Captured %1$s. Values are byte-for-byte copies of the old site, with %2$d recorded deviation(s).', 'wellspring' ),
				esc_html( isset( $data['meta']['captured_utc'] ) ? $data['meta']['captured_utc'] : 'unknown' ),
				count( isset( $data['meta']['deviations'] ) ? $data['meta']['deviations'] : array() )
			);
			?>
		</p>

		<?php if ( ! empty( $data['meta']['deviations'] ) ) : ?>
			<div class="notice notice-info"><p><strong><?php esc_html_e( 'Recorded deviations from byte-for-byte:', 'wellspring' ); ?></strong></p>
			<ul style="margin:0 0 .8em 1.4em;list-style:disc">
				<?php foreach ( $data['meta']['deviations'] as $dev ) : ?>
					<li>
						<code><?php echo esc_html( $dev['path'] ); ?></code> (<?php echo esc_html( $dev['field'] ); ?>) —
						<?php esc_html_e( 'encoding fix', 'wellspring' ); ?>
					</li>
				<?php endforeach; ?>
			</ul>
			</div>
		<?php endif; ?>

		<?php if ( $results ) : ?>
			<div class="notice notice-success">
				<p><strong><?php esc_html_e( 'Import run.', 'wellspring' ); ?></strong></p>
				<ul style="margin:0 0 .8em 1.4em;list-style:disc">
					<?php foreach ( $results as $line ) : ?>
						<li><?php echo esc_html( $line ); ?></li>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php endif; ?>

		<form method="post">
			<?php wp_nonce_field( 'ws_seo_import' ); ?>

			<table class="widefat striped" style="margin-top:1em">
				<thead>
					<tr>
						<th style="width:12%"><?php esc_html_e( 'Old URL', 'wellspring' ); ?></th>
						<th style="width:14%"><?php esc_html_e( 'Target', 'wellspring' ); ?></th>
						<th style="width:6%"><?php esc_html_e( 'Field', 'wellspring' ); ?></th>
						<th><?php esc_html_e( 'Current', 'wellspring' ); ?></th>
						<th><?php esc_html_e( 'Incoming', 'wellspring' ); ?></th>
						<th style="width:11%"><?php esc_html_e( 'Status', 'wellspring' ); ?></th>
					</tr>
				</thead>
				<tbody>
				<?php foreach ( $plan as $row ) : ?>
					<?php foreach ( $row['fields'] as $field => $info ) : ?>
						<tr>
							<td><code><?php echo esc_html( $row['source_path'] ); ?></code></td>
							<td><?php echo esc_html( $row['target']['label'] ); ?></td>
							<td><?php echo esc_html( $field ); ?></td>
							<td style="word-break:break-word">
								<?php echo '' === $info['current'] ? '<em style="color:#6B7873">empty</em>' : esc_html( $info['current'] ); ?>
							</td>
							<td style="word-break:break-word">
								<?php echo '' === $info['incoming'] ? '<em style="color:#6B7873">—</em>' : esc_html( $info['incoming'] ); ?>
								<?php if ( $row['deviation'] && 'description' === $field ) : ?>
									<span style="display:inline-block;margin-left:.3em;font-size:11px;color:#8A2B1D">(<?php esc_html_e( 'deviation', 'wellspring' ); ?>)</span>
								<?php endif; ?>
							</td>
							<td>
								<?php
								list( $text, $fg, $bg ) = $labels[ $info['status'] ];
								printf(
									'<span style="display:inline-block;padding:1px 6px;border-radius:2px;font-size:11px;color:%s;background:%s">%s</span>',
									esc_attr( $fg ),
									esc_attr( $bg ),
									esc_html( $text )
								);
								?>
								<?php if ( 'conflict' === $info['status'] ) : ?>
									<br>
									<label style="font-size:11px">
										<input type="checkbox" name="ws_overwrite[]" value="<?php echo esc_attr( $row['index'] . ':' . $field ); ?>">
										<?php esc_html_e( 'overwrite', 'wellspring' ); ?>
									</label>
								<?php endif; ?>
								<?php if ( $info['note'] ) : ?>
									<p class="description" style="margin:.3em 0 0;font-size:11px"><?php echo esc_html( $info['note'] ); ?></p>
								<?php endif; ?>
							</td>
						</tr>
					<?php endforeach; ?>
				<?php endforeach; ?>
				</tbody>
			</table>

			<p style="margin-top:1em">
				<button type="submit" name="ws_seo_import" value="1" class="button button-primary">
					<?php esc_html_e( 'Write the changes above', 'wellspring' ); ?>
				</button>
				<span class="description" style="margin-left:.6em">
					<?php esc_html_e( 'Rows marked Unchanged, Nothing to port or No target are skipped. Conflicts are skipped unless ticked.', 'wellspring' ); ?>
				</span>
			</p>
		</form>
	</div>
	<?php
}

/**
 * Perform the writes and return a human-readable log.
 *
 * @param array $entries   Data-file entries.
 * @param array $overwrite List of "index:field" strings the user ticked.
 * @return string[]
 */
function wellspring_seo_import_run( $entries, $overwrite ) {
	$log     = array();
	$written = 0;
	$skipped = 0;
	$blocked = 0;

	foreach ( $entries as $i => $entry ) {
		$target = wellspring_seo_import_target( $entry );
		$path   = isset( $entry['source_path'] ) ? $entry['source_path'] : '#' . $i;

		if ( 'missing' === $target['kind'] ) {
			$log[]   = sprintf( '%s — NO TARGET: %s', $path, isset( $target['error'] ) ? $target['error'] : '' );
			$blocked++;
			continue;
		}

		foreach ( array( 'title', 'description' ) as $field ) {
			$incoming = isset( $entry[ $field ] ) ? (string) $entry[ $field ] : '';
			$info     = wellspring_seo_import_plan_field( $target, $field, $incoming );

			if ( in_array( $info['status'], array( 'nothing', 'unchanged' ), true ) ) {
				$skipped++;
				continue;
			}

			if ( 'conflict' === $info['status'] && ! in_array( $i . ':' . $field, $overwrite, true ) ) {
				$log[] = sprintf( '%s (%s) — CONFLICT, left alone.', $path, $field );
				$blocked++;
				continue;
			}

			if ( wellspring_seo_import_write( $target, $field, $incoming ) ) {
				$log[] = sprintf( '%s (%s) — written.', $path, $field );
				$written++;
			} else {
				$log[] = sprintf( '%s (%s) — WRITE FAILED (is ACF active?).', $path, $field );
				$blocked++;
			}
		}
	}

	array_unshift(
		$log,
		sprintf(
			/* translators: 1: written, 2: skipped, 3: blocked */
			__( '%1$d written, %2$d already correct, %3$d needing attention.', 'wellspring' ),
			$written,
			$skipped,
			$blocked
		)
	);

	return $log;
}
